## server
server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    mbeanregistry:
      enabled: on

## actuator
management:
  info:
    java:
      enabled: on
    env:
      enabled: on
    os:
      enabled: on
  endpoints:
    web:
      exposure:
        include: "*"

## spring
spring:
  application:
    name: bob-hot-article
  main:
    banner-mode: log
    allow-bean-definition-overriding: on
  data:
    redis:
      repositories:
        enabled: off
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: basic
  threads:
    virtual:
      enabled: on
  kafka:
    bootstrap-servers: ${kafka_servers:localhost:9092}
    consumer:
      group-id: ${kafka_consumer_group_id}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: off


## eureka
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    enabled: ${discovery_enabled:off}
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${discovery_host:http://localhost:8761/eureka}


## malgn
malgn:
  enabled: on
  auth:
    user:
      enabled: on
      host: ${auth-user-host:http://localhost:8080}
  redis:
    enabled: on
    host: ${redis_host:redis://localhost:6379}
  notification:
    enabled: on
    host: ${notification_host:http://localhost:8080}

## logging
logging:
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: ${logs_path}/${spring.application.name}.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%-5p} ${PID} --- [%15.15t] %-40.40logger{39} :%06L : %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%-5p} ${PID} --- [%15.15t] %-40.40logger{39} :%06L : %m%n"
  logback:
    rollingpolicy:
      file-name-pattern: "${logs_path}/%d{yyyy-MM-dd}/${spring.application.name}.%d{yyyy-MM-dd}.%i.log"
      max-file-size: 10MB
      max-history: ${log_max_history:10}
  level:
    root: info
    web: ${logs_web_level:info}
    com.malgn: ${logs_malgn_level:info}